#!/bin/bash
#
#SBATCH --job-name=randomdistance
#SBATCH --output=randomdistance_job.out
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=12
#SBATCH --partition=amd-hdr100
#SBATCH --time=5:00:00
#SBATCH --mem-per-cpu=4069

# load your Anaconda module here and activate your virtual environment (if needed)
set -e
source /home/ashovon/venvs/brainph/bin/activate

python -u /home/ashovon/brainph/distance_calculation_random.py --method ws --start 1 --end 316 --distance y --mds y